name: build-and-push-image
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: harci-backend
  REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR (admin creds)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image tags
        run: |
          echo "Pushed:"
          echo "  $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}"
          echo "  $REGISTRY/$IMAGE_NAME:latest"
