name: build-and-push-image
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: harci-backend
  REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR (admin creds)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build image (classic docker)
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA} -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA}
          docker push $REGISTRY/$IMAGE_NAME:latest
